- alias: 'Keep AuricÄƒ cool'
  trigger:
    platform: time_pattern
    minutes: '*'
    seconds: '0'
  action:
    entity_id: switch.ac
    service_template: >
      {% if states.sensor.living_temperature.state | float > states.input_number.max_temp | float and states.switch.ac.state == 'off' %}
      switch.turn_on
      {% elif states.sensor.living_temperature.state | float < states.input_number.min_temp | float and states.switch.ac.state == 'on' %}
      switch.turn_off
      {% else %}
      script.do_nothing
      {% endif %}

- alias: 'Remote: AC'
  trigger:
    platform: state
    entity_id: sensor.0x000d6ffffe0b266b_action
    to: 'toggle'
  action:
    entity_id: switch.ac
    service: switch.toggle

- alias: 'Remote: Light'
  trigger:
    platform: state
    entity_id: sensor.0x000d6ffffe0b266b_action
    to: 'brightness_up_click'
  action:
    entity_id: light.living
    service: light.toggle

